image: node:latest
pages:
 stage: deploy
 script:
  - cd UMFit-WebApp/UMFit-Client/UMFit-App
  - npm install -g ionic cordova
  - npm install
  # we need to set the basePath to the sub dir
  - ionic build --prod
  - mkdir ../../../public
  - cp -r build/* ../../../public
  - cp ../../../public/index.html ../../../public/404.html"
 artifacts:
  paths:
  - public
 only:
  - master
