image: node:latest
pages:
 stage: deploy
 script:
  - cd UMFit-WebApp/UMFit-Client/UMFit-App
  - npm install -g ionic cordova
  - npm install
  # we need to set the basePath to the sub dir
  - ionic build --prod
 artifacts:
  paths:
  - UMFit-WebApp/UMFit-Client/UMFit-App/build
 only:
  - master
