image: node:latest
pages:
 stage: deploy
 script:
  - cd UMFit-WebApp/UMFit-Client/UMFit-App
  - npm install -g ionic cordova
  - npm install
  # we need to set the basePath to the sub dir
  - ionic build --prod
  - rm -rf public
  - mkdir public
  - cp -r build/* public
 artifacts:
  paths:
  - UMFit-WebApp/UMFit-Client/UMFit-App/public
 only:
  - master
