pages:
 image: node:latest
 stage: deploy
 script:
  - cd /UMFit-WebApp/UMFit-Client/UMFit-App/
  - npm install -g ionic cordova
  - npm install
  # we need to set the basePath to the sub dir
  - ionic build --prod -- --base-href="https://devzizu.gitlab.io/li4_umfit"
  - rm -rf public
  - mkdir public
  - cp -r www/* public
 artifacts:
  expire_in: 1 week
  paths:
  - public
 only:
  - dev
